### ISSUE TITLE
FATAL: showlinenum: Line info found before path info.

### ISSUE THREAD

**Issue by markburns** [jay/showlinenum#4]
Hi, I can see that this is intentionally output in certain circumstances by glancing through the source, but I'm not sure what I can do to resolve this as a user?

Is there some specific git diff output format or config I need to set to be able to use this?

**Comment by jay** [comment]
That error shouldn't be shown. Path info must come before line info. Example

--- a/foo <--- old path info
+++ b/foo <--- current path info
@@ -0,0 +1 @@ <--- line info
+foo


How are you running it?

**Comment by markburns** [comment]
Just as per the README. Maybe it’s some difference in git version or config

**Comment by jay** [comment]
Can you give me a way to reproduce?

**Comment by markburns** [comment]
I've narrowed it down to this. (I use https://github.com/skwp/dotfiles so I didn't write this config)

```
[diff]
  # Git diff will use (i)ndex, (w)ork tree, (c)ommit and (o)bject
  # instead of a/b/c/d as prefixes for patches
  mnemonicprefix = true
```

**Comment by markburns** [comment]
```
➜ git --version
git version 2.20.1
```

**Comment by jay** [comment]
Thanks for that. Currently the script does not support mnemonics, I will see if I can add it.

**Comment by markburns** [comment]
Awesome thanks for the fix!
